version: "3.7"

services:
  ###########################################################################
  #######                          PAYANAM                            #######
  ###########################################################################
  payanam:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - ./routes:/app/routes
      - ./locked-routes:/app/locked-routes
      - ./reports:/app/reports
      - ./logs:/app/logs
      - ./gtfs:/app/gtfs
      - ./config:/app/config
      - ./uploads:/app/uploads
    networks:
      - intranet

networks:
  intranet:
